# CF Template to create VPC with parameters
AWSTemplateFormatVersion: 2010-09-09
Description: "Creation of VPC & subnets using the Cloud Formation Template"


Resources:
# Create a IGW
  myIGW:
    Type: "AWS::EC2::InternetGateway"
    Properties: 
      Tags:
        - 
          Key: "Name"
          Value: "myIGW"
# Create a new VPC
  
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        -
          Key: "Name"
          Value: "myVPC"
        -
          Key: "Client"
          Value: "CTR"

#Attach IGW to VPC

  myGatewayAttach:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref myIGW
      VpcId: !Ref myVPC

#Create new public route table

  myRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref myVPC  

# Add route to the internet via IGW to the public route table

  myRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref myIGW
      RouteTableId: !Ref myRouteTable



  myPublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: "Name"
          Value: "myPublicSubnet"
      VpcId: !Ref myVPC
  

# Assocaite public route tabe to public subnet

  myRouteAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      RouteTableId: !Ref myRouteTable
      SubnetId: !Ref myPublicSubnet      
  
  myPrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "10.0.2.0/24"
      # MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: "Name"
          Value: "myPrivateSubnet"
      VpcId: !Ref myVPC

# Create Webserver EC2 instance in public subnet

  myWebEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-e689729e
      InstanceType: t2.micro 
      SubnetId: !Ref myPublicSubnet

# Stack output values

Outputs:
  VPCId:
    Value: !Ref myVPC
  VPCCIDRBlock:
    Value: !GetAtt myVPC.CidrBlock
  PublicSubnetID:
    Value: !Ref myPublicSubnet
  PublicSubnetAZ:
    Value: !GetAtt myPublicSubnet.AvailabilityZone
  PrivateSubnetID:
    Value: !Ref myPublicSubnet
  PrivateSubnetAZ:
    Value: !GetAtt myPrivateSubnet.AvailabilityZone
  WebserverID:
    Value: !Ref myWebEC2
  WebServerPublicIP:
    Value: !GetAtt myWebEC2.PublicIp